### ISSUE TITLE
Error when detector train custom object

### ISSUE THREAD

**Issue by cuongngm** [phamdinhkhanh/darknetGoogleColab#1]
![6](https://user-images.githubusercontent.com/53366035/79039720-76562e80-7c0d-11ea-89f0-978a7d7d0120.png)
Em làm theo hướng dẫn bài 25 trên blog của anh, đến bước này thì cứ bị treo như vậy mà không thấy train.  Mong được a hỗ trợ ạ

**Comment by MacNgoc** [comment]
mình cũng bị hệt như bạn, model không train tẹo nào, mình chờ tầm 10 tiếng thì google colab tự tắt, file yolov3-5c.log không có gì bên trong cả, backup cũng không có gì. Mình làm đi làm lại 2 lần, nhưng kết quả vẫn như vậy

**Comment by cuongngm** [comment]
> mình cũng bị hệt như bạn, model không train tẹo nào, mình chờ tầm 10 tiếng thì google colab tự tắt, file yolov3-5c.log không có gì bên trong cả, backup cũng không có gì. Mình làm đi làm lại 2 lần, nhưng kết quả vẫn như vậy

mình cx 2 ngày r chưa fix đc, bạn train object khác hay chạy lại bài a Khánh

**Comment by phamdinhkhanh** [comment]
Model vẫn hoạt động đó mọi người. Mọi người nghĩ ko train là do mình lưu log vào file yolov3-5c.log (trong code là đoạn trỏ vào > yolov3-5c.log ở cuối) nên trên màn hình sẽ không hiển thị.

Mọi người có thể mở một notebook khác và chạy file plotTrainLoss.py để kiểm
tra accuracy qua từng epochs.

Vào 19:42, Th 2, 13 thg 4, 2020 cuonghip0908 <notifications@github.com> đã
viết:

**Comment by manhhung99** [comment]
Em dùng bài hướng dẫn của anh để training với bộ dữ liệu nhận diện có đeo khẩu trang hay không? Nhưng em bị lỗi, không biết sửa sao? Mong anh giúp đỡ ạ ! @phamdinhkhanh 

![Screenshot from 2020-06-30 10-07-46](https://user-images.githubusercontent.com/52267054/86079220-38ed9880-baba-11ea-9b6a-e080b6f46b7b.png)

**Comment by MacNgoc** [comment]
Có một lệnh mà bạn khánh quên không viết là makefile trước khi chạy.
Bạn thử chạy "!make" trước khi chạy lệnh "!./darknet detector train " xem sao.

**Comment by manhhung99** [comment]
Cảm ơn bạn nhiều!

**Comment by manhhung99** [comment]
Sau khi thêm lệnh ```!make```  như @MacNgoc gợi ý thì đã chạy được, nhưng có một vấn đề là mình chẳng thấy file.weights đâu cả? Trong thư mục backup trống không ? Mọi người giúp mình với ạ !  @phamdinhkhanh
![Screenshot from 2020-07-02 14-44-25](https://user-images.githubusercontent.com/52267054/86333534-3afc5680-bc76-11ea-8968-2b8fa568c0c6.png)
![Screenshot from 2020-07-02 14-43-25](https://user-images.githubusercontent.com/52267054/86333538-3cc61a00-bc76-11ea-9a0f-f78ddb57a034.png)

**Comment by trung-nguyen-code** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/63198270/87526276-db11a100-c6b4-11ea-933d-08237f1d1a46.png)
E chào a Khánh. Em đã làm theo hướng dẫn của a nhưng đến khi train thì gặp vấn đề, google colab báo lỗi đã set batch sai. Mong anh và mọi người giúp em. Em cảm ơn ạ.

**Comment by cuongngm** [comment]
> ![Screenshot (19)](https://user-images.githubusercontent.com/63198270/87526276-db11a100-c6b4-11ea-933d-08237f1d1a46.png)
> E chào a Khánh. Em đã làm theo hướng dẫn của a nhưng đến khi train thì gặp vấn đề, google colab báo lỗi đã set batch sai. Mong anh và mọi người giúp em. Em cảm ơn ạ.

Set lại batch size cả subdivision trong file cfg nhé ( để 64,32), bạn đang để (1,1). hoặc uncomment dòng training và thêm # vào dòng testing

**Comment by trung-nguyen-code** [comment]
[

**Comment by trung-nguyen-code** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/63198270/87621963-3c388380-c74c-11ea-8bcd-b548bc2923b6.png)
sau khi sửa lại như a  @cuonghip0908  thì quá trình train đã chạy. Nhưng nó lại có mấy dòng báo incorrect với warning là sao ạ? Liệu có vấn đề gì ko ạ? Em cảm ơn.

**Comment by trung-nguyen-code** [comment]
@cuonghip0908  Sau khi được a  giúp đỡ thì e đã train được r. Nhưng mà nó lại báo incorrect thế này thì có sao ko ạ?
![Screenshot (20)](https://user-images.githubusercontent.com/63198270/87622185-bff27000-c74c-11ea-9c71-3705c5338f01.png)

**Comment by trung-nguyen-code** [comment]
Ngoài ra trong quá trình train, sau 1000 img đầu tiên e đã kiểm tra trong folder backup ko tháy có j cả?
